// Generated by JoltC-generate

JPC_IMPL void JPC_ConstraintSettings_to_jpc(JPC_ConstraintSettings* outJpc, const JPH::ConstraintSettings* inJph) {
	outJpc->Enabled = inJph->mEnabled;
	outJpc->ConstraintPriority = inJph->mConstraintPriority;
	outJpc->NumVelocityStepsOverride = inJph->mNumVelocityStepsOverride;
	outJpc->NumPositionStepsOverride = inJph->mNumPositionStepsOverride;
	outJpc->DrawConstraintSize = inJph->mDrawConstraintSize;
	outJpc->UserData = inJph->mUserData;
}

JPC_IMPL void JPC_ConstraintSettings_to_jph(const JPC_ConstraintSettings* inJpc, JPH::ConstraintSettings* outJph) {
	outJph->mEnabled = inJpc->Enabled;
	outJph->mConstraintPriority = inJpc->ConstraintPriority;
	outJph->mNumVelocityStepsOverride = inJpc->NumVelocityStepsOverride;
	outJph->mNumPositionStepsOverride = inJpc->NumPositionStepsOverride;
	outJph->mDrawConstraintSize = inJpc->DrawConstraintSize;
	outJph->mUserData = inJpc->UserData;
}

JPC_API void JPC_ConstraintSettings_default(JPC_ConstraintSettings* value) {
	JPH::ConstraintSettings defaultValue{};
	JPC_ConstraintSettings_to_jpc(value, &defaultValue);
}

