#pragma once
// Generated by JoltC-generate

typedef struct JPC_ConstraintSettings {
	bool Enabled;
	uint32_t ConstraintPriority;
	uint NumVelocityStepsOverride;
	uint NumPositionStepsOverride;
	float DrawConstraintSize;
	uint64_t UserData;
} JPC_ConstraintSettings;

JPC_API void JPC_ConstraintSettings_default(JPC_ConstraintSettings* value);

