#pragma once
// Generated by JoltC-generate

typedef uint32_t JPC_ConstraintSpace;
const JPC_ConstraintSpace JPC_CONSTRAINT_SPACE_LOCAL_TO_BODY_COM = 0;
ENSURE_ENUM_EQ(JPC_CONSTRAINT_SPACE_LOCAL_TO_BODY_COM, JPH::EConstraintSpace::LocalToBodyCOM)
const JPC_ConstraintSpace JPC_CONSTRAINT_SPACE_WORLD_SPACE = 1;
ENSURE_ENUM_EQ(JPC_CONSTRAINT_SPACE_WORLD_SPACE, JPH::EConstraintSpace::WorldSpace)

typedef struct JPC_ConstraintSettings {
	bool Enabled;
	uint32_t ConstraintPriority;
	uint NumVelocityStepsOverride;
	uint NumPositionStepsOverride;
	float DrawConstraintSize;
	uint64_t UserData;
} JPC_ConstraintSettings;

JPC_API void JPC_ConstraintSettings_default(JPC_ConstraintSettings* value);

typedef struct JPC_FixedConstraintSettings {
	JPC_ConstraintSettings ConstraintSettings;
	JPC_ConstraintSpace Space;
	bool AutoDetectPoint;
	JPC_RVec3 Point1;
	JPC_Vec3 AxisX1;
	JPC_Vec3 AxisY1;
	JPC_RVec3 Point2;
	JPC_Vec3 AxisX2;
	JPC_Vec3 AxisY2;
} JPC_FixedConstraintSettings;

JPC_API void JPC_FixedConstraintSettings_default(JPC_FixedConstraintSettings* value);

